version: '3.8'

services:
  cybersafe:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../app:/app/app
      - ../tests:/app/tests
      - ../.cache:/app/.cache
    environment:
      - PYTHONUNBUFFERED=1
